kind: pipeline
name: default
type: docker

trigger:
  event:
    - custom

clone:
  disable: true

steps:
  - name: deploy
    # image: ghcr.io/grsky360/ilio-tech
    image: grsky360/ilio-tech
    environment:
      DEPLOYMENT_PATH: /deployment
    volumes:
      - name: deployment
        path: /deployment

volumes:
- name: deployment
  host:
    path: /yang/data/static-pages/ilio.tech
