kind: pipeline
name: default

concurrency:
  limit: 1

steps:
  - name: build
    image: node:alpine
    volumes:
      - name: deployment
        path: /deployment
    commands:
      - yarn
      - yarn build
      - mkdir -p /deployment && rm -rf /deployment/*
      - mv public/* /deployment/

volumes:
- name: deployment
  host:
    path: /yang/data/static-pages/ilio.tech
